# GitHub Actions Workflow: Scrape Flights + Send to JetSet Hacks Webhook
# 
# This workflow:
# 1. Scrapes flight data using Amadeus + Kiwi APIs (your existing scrape.py)
# 2. Sends data to Supabase webhook (webhook_sender.py)
# 3. Runs every 3 hours automatically
#
# TO USE THIS FILE:
# 1. Copy this file to: .github/workflows/scrape-and-webhook.yml
# 2. That's it! GitHub will auto-run it every 3 hours

name: Scrape Flights & Update JetSet Hacks

on:
  schedule:
    - cron: "0 */3 * * *"       # Every 3 hours at minute 0
  workflow_dispatch: {}         # Allow manual runs from GitHub Actions tab


jobs:
  scrape-and-webhook:
    runs-on: ubuntu-latest
    env:
      # These secrets are already configured in your repo
      TEQUILA_API_KEY: ${{ secrets.TEQUILA_API_KEY }}
      AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
      AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper_bot/requirements.txt
          pip install requests  # For webhook sender

      - name: Run scraper
        run: |
          echo "🔍 Scraping flights using Amadeus + Kiwi APIs..."
          python scraper_bot/scrape.py
          echo "✅ Scraping completed!"

      - name: Send to JetSet Hacks webhook
        run: |
          echo "🚀 Sending flight data to Supabase webhook..."
          python scraper_bot/webhook_sender.py
          echo "✅ Webhook delivery completed!"

      - name: Commit updated JSON (optional backup)
        env:
          
        if: always()
        run: |
          echo "================================================"
          echo "  Flight Data Pipeline Status"
          echo "================================================"
          echo "✅ Scraper: Completed"
          echo "✅ Webhook: Delivered to JetSet Hacks"
          
          echo "================================================"
          #Ready to Run
